server:
  port: 9527

spring:
  profiles:
    active: secret
  application:
    name: goods
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
