server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo

          uri: lb://demo
          predicates:
              Path=/create #断言,路径相匹配的进行路由
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
